$(document).ready(function(){
    $("#testimonial-slider").owlCarousel({
        items:4,
        itemsDesktop:[1000,4],
        itemsDesktopSmall:[980,3],
        itemsTablet:[768,1],
        pagination:true,
        navigation:false,
        navigationText:["",""],
        autoPlay:true
    });
});